id: IE9A5E136
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T17:57:40+00:00'
last_modified: '2022-06-08T13:07:54.437111+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W13528
  title: གསུང་འབུམ། བློ་བཟང་དམ་ཆོས་རྒྱ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    A34C:
      image_group_id: I3099
      title: ''
      total_pages: 476
      order: 1
      base_file: A34C.txt
    64E9:
      image_group_id: I3100
      title: ''
      total_pages: 492
      order: 2
      base_file: 64E9.txt
    18D3:
      image_group_id: I3101
      title: ''
      total_pages: 479
      order: 3
      base_file: 18D3.txt
    91FE:
      image_group_id: I3102
      title: ''
      total_pages: 531
      order: 4
      base_file: 91FE.txt
    '7759':
      image_group_id: I3103
      title: ''
      total_pages: 550
      order: 5
      base_file: 7759.txt
    4C06:
      image_group_id: I3104
      title: ''
      total_pages: 542
      order: 6
      base_file: 4C06.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
