id: IE9A5E136
legacy_id: P010374
ocr_import_info:
  bdrc_scan_id: W13528
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T17:53:51'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T12:52:30.942399+00:00'
last_modified: 2022-08-30 20:56:54.802619
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W13528
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW13528
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་བཟང་དམ་ཆོས་རྒྱ་མཚོ།
  author: བློ་བཟང་དམ་ཆོས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.7557744384177977
  ocr_word_median_confidence_index: 0.8399999737739563
quality: null
bases:
  I3100:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3100
      total_pages: 492
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3100.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7536904692704239
    legacy_id: v002
  I3101:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3101
      total_pages: 479
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3101.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7348001898248471
    legacy_id: v003
  I3099:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3099
      total_pages: 476
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3099.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7125091525081084
    legacy_id: v001
  I3102:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3102
      total_pages: 531
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3102.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.7992846211268316
    legacy_id: v004
  I3104:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3104
      total_pages: 542
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I3104.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.7525749904393618
    legacy_id: v006
  I3103:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3103
      total_pages: 550
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I3103.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.7835608305985324
    legacy_id: v005
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
